add slots that are rendered if there are no options or search results and improve how search works
singularit-de/multiselect pull request #43
Opened 2022-07-12 13:08 UTC by Moerlin1337

By default the slots display the value of the noOptionsText or noResultsText props.

2022-08-03 14:52 UTC, Moerlin1337 commented
covers issues #42 #44 #46

2022-08-29 17:07 UTC, Moerlin1337 commented
also covers issue #47

2022-08-30 09:00 UTC, OrbisK requested changes
Komm gern nochmal auf mich zu @Moerlin1337

2022-08-30 09:00 UTC, OrbisK commented on src/Multiselect.vue
ich würde hier gern noch ein paar functions exposen. Für mehr infos bitte an mich wenden

2022-10-19 09:23 UTC, OrbisK commented
@coronoro ready to merge?

2022-10-19 09:48 UTC, OrbisK approved these changes

2022-10-19 09:48 UTC, merged